### ISSUE TITLE
Peer to peer code review Block 5

### ISSUE THREAD

**Issue by christianonoh** [J-C-S-V/The-Ethics-of-AI-conference#1]
Good job so far! Here are a few suggestions on how you can make your code better, these are optional but would be nice if implemented:
- Use CSS variable so you won’t have to keep repeating the actual values, plus it makes your code easier to manage and modify. You can check more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).
- Add meta tags like description, keywords etc in your index file to increase your SEO score.

**Comment by J-C-S-V** [comment]
Thank you so much for the feedback!!!!!!
